### ISSUE TITLE
ShaderCompilationException in Border demo

### ISSUE THREAD

**Issue by aweary** [revery-ui/revery#414] opened 2019-03-25 05:18 UTC
I just cloned and built from `master` and encountered this error when trying to run the Example application and access the Border view. I verified all other examples work. I'm on macOS `10.14.3`.

```
Fatal error: exception Revery_Shaders__Shader.ShaderCompilationException("ERROR: 0:7: 
Incompatible types in initialization (and no available implicit conversion)\nERROR: 0:8:
Use of undeclared identifier 'halfRes'\nERROR: 0:8: Use of undeclared identifier
'halfRes'\nERROR: 0:9: Use of undeclared identifier 'box'\nERROR: 0:10: Use of undeclared
identifier 'delta'\nERROR: 0:10: Use of undeclared identifier 'box'\nERROR: 0:12:
Use of undeclared identifier 'alpha'\n")
```

Happy to provide more debug information if needed!

**Comment by bryphe** [comment] 2019-03-27 02:08
Thanks @aweary for the report!

Looks like there is a bug in the `BorderRadiusShader` here: https://github.com/revery-ui/revery/blob/3cb90685cbcf3a82ce27af3e960483e4d75391aa/src/Draw/BorderRadiusShader.re#L50

Able to reproduce on my Manjaro Linux box.

We're using `float halfRes = 0.5 * uResolution.xy`, but `uResolution` is a `vec2`, so `halfRes` is actually a `vec2` also. So seems like there is a bug in the logic here. 

Might be addressed by @zbaylin 's latest work on the border radius shader, though?

**Comment by msvbg** [comment] 2019-04-15 02:19
This was closed in https://github.com/revery-ui/revery/pull/436.

**Comment by bryphe** [comment] 2019-04-15 15:08
Thanks @msvbg !

**Closed by bryphe** 2019-04-15 15:08 UTC
Labels: bug
